name: experiments-measuring-dq
channels:
- conda-forge
dependencies:
- python=3.6
- numpy=1.15.4
- pandas=1.0.3
- scikit-learn=0.23.1
- matplotlib=3.2.1
- seaborn=0.10.1
- scipy=1.4.1
- requests=2.23.0
- notebook=6.0.3
- jupyterlab=2.1.2
- cudatoolkit=9.0
- tensorflow-gpu=1.12.0
- keras=2.2.4
- nltk=3.5